### ISSUE TITLE
Hide/remove menu item types

### ISSUE THREAD

**Issue by MaxNozhkin** [Flynsarmy/oc-menu-plugin#10]
Hello!
Could you help me, how to hide or remove different types of links for "Choose a type"?
Page, Partial, Link for example.

I can to add different in my plugin, in func "register_flynsarmy_menu_item_types", but now i need to remove.

**Comment by Flynsarmy** [comment]
Not sure if you can. Send a PR to add an event here somewhere https://github.com/Flynsarmy/oc-menu-plugin/blob/master/classes/MenuManager.php#L120 then you can hook into it from your plugin.
