### ISSUE TITLE
Please make menu field labels translate-able

### ISSUE THREAD

**Issue by MatissJanis** [Flynsarmy/oc-menu-plugin#5]
E.g. use Rainlab.translate

**Comment by fobus42** [comment]
They are translateable but doesn't work.

**Comment by Flynsarmy** [comment]
Yea I tried adding translation support when I first released the plugin but it doesn't seem to work in modals. You'll have to leave an issue with that plugin.

**Comment by MatissJanis** [comment]
Why was this issue closed? It's not fixed and a solution hasn't been offered.

**Comment by Flynsarmy** [comment]
It's not an issue on my end. That's why the issue was closed.
